In [30]:
import numpy as np
import pandas as pd

Question 1: Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays 

In [13]:
a = np.array([1,2,3,4,5])
b= np.array([4,5,6,7,8])
c= np.array([2,3,4,5,1])

print(np.equal(a,c))
print(np.greater_equal(c,a))
print(np.less_equal(c,a))
print(np.less(a,c))
print(np.less_equal(c,b))
print(np.greater(a,b))

[False False False False False]
[ True  True  True  True False]
[False False False False  True]
[ True  True  True  True False]
[ True  True  True  True  True]
[False False False False False]


Question 2: 
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives 

In [15]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
print(np.ones(10)*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Question 3: 
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array 

In [18]:
a=[[1,2],[2,3],[3,4]]
print(np.sum(a))

15


In [21]:
print(np.sum(a,axis=0))

[6 9]


In [22]:
print(np.sum(a,axis=1))

[3 5 7]


Question 4: 
Write a NumPy program to add, subtract, multiply, divide arguments element-wise

In [25]:
print(np.add(1,3))
print(np.subtract(1,3))
print(np.multiply(2,3))
print(np.divide(4,2))

4
-2
6
2.0


Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree

In [29]:
a=[1,3,5,7,9]
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849]
[ 0.54030231 -0.9899925   0.28366219  0.75390225 -0.91113026]
[ 1.55740772 -0.14254654 -3.38051501  0.87144798 -0.45231566]


Question 6:
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels

In [41]:
emp_data  = {'Code_Name': ['AE','BE','CE'],'ID': [1, 2, 3],'Level': [8,9,10]}
labels = ['E1', 'E2','E3']

df = pd.DataFrame(emp_data , index=labels)
print(df)

   Code_Name  ID  Level
E1        AE   1      8
E2        BE   2      9
E3        CE   3     10


Question 7: 
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [36]:
print(df[['Code_Name','ID']])

   Code_Name  ID
E1        AE   1
E2        BE   2
E3        CE   3


Question 8: 
Write a Pandas program to join the two given dataframes along rows and assign all data

In [38]:
Class_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

Class_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

print(pd.concat([Class_data1,Class_data2]))

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201


Question 9: 
Write a Pandas program to detect missing values of a given DataFrame. Display True or False

In [46]:
df1=pd.DataFrame({
    'Student_ID':[1,np.nan,2,np.nan,3,np.nan]
})
print(df1.isna())

   Student_ID
0       False
1        True
2       False
3        True
4       False
5        True


Question 10:
Write a Pandas program to create and display a one-dimensional array-like object containing an array of data

In [47]:
a = pd.Series([1,2,3,4])
print(a)

0    1
1    2
2    3
3    4
dtype: int64
